language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script:
  - bin/test
notifications:
  email:
    recipients:
      - support@lists.affinitic.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#affinitic"
    on_success: change
    on_failure: always
