INSERT
    INTO hebergement(heb_pk,
    heb_code_gdw,
    heb_nom,
    heb_adresse,
    heb_localite,
    heb_code_cgt,
    heb_cgt_cap_min,
    heb_cgt_cap_max,
    heb_cgt_nbre_chmbre,
    heb_etat,
    heb_site_public,
    heb_groupe,
    heb_gdw,
    heb_nbre_epis,
    heb_tarif_we_bs,
    heb_tarif_we_ms,
    heb_tarif_we_hs,
    heb_tarif_sem_bs,
    heb_tarif_sem_ms,
    heb_tarif_sem_hs,
    heb_tarif_garantie,
    heb_tarif_divers,
    heb_descriptif_fr,
    heb_descriptif_uk,
    heb_descriptif_nl,
    heb_descriptif_de,
    heb_descriptif_it,
    heb_pointfort_fr,
    heb_pointfort_uk,
    heb_pointfort_nl,
    heb_pointfort_de,
    heb_pointfort_it,
    heb_equipement_fr,
    heb_equipement_uk,
    heb_equipement_nl,
    heb_equipement_de,
    heb_equipement_it,
    heb_photo,
    heb_com_fk,
    heb_cgt_fk,
    heb_typeheb_fk,
    heb_pro_fk,
    heb_theme_fk,
    heb_label_fk,
    heb_tenis_distance,
    heb_nautisme_distance,
    heb_sky_distance,
    heb_rando_distance,
    heb_piscine_distance,
    heb_peche_distance,
    heb_equitation_distance,
    heb_velo_distance,
    heb_vtt_distance,
    heb_ravel_distance,
    heb_taxe_montant,
    heb_forfait_montant,
    heb_tarif_we_3n,
    heb_tarif_we_4n,
    heb_tarif_semaine_fin_annee,
    heb_lit_1p,
    heb_lit_2p,
    heb_lit_sup,
    heb_lit_enf,
    heb_distribution_fr,
    heb_distribution_nl,
    heb_distribution_it,
    heb_distribution_uk,
    heb_distribution_de,
    heb_gare_distance,
    heb_restaurant_distance,
    heb_commerce_distance,
    heb_tarif_chmbr_avec_dej_1p,
    heb_tarif_chmbr_avec_dej_2p,
    heb_tarif_chmbr_avec_dej_3p,
    heb_tarif_chmbr_sans_dej_1p,
    heb_tarif_chmbr_sans_dej_2p,
    heb_tarif_chmbr_sans_dej_3p,
    heb_tarif_chmbr_dej_1p,
    heb_tarif_chmbr_dej_2p,
    heb_tarif_chmbr_dej_3p,
    heb_tarif_chmbr_table_hote_1p,
    heb_tarif_chmbr_table_hote_2p,
    heb_tarif_chmbr_table_hote_3p,
    heb_tarif_chmbr_autre_1p,
    heb_tarif_chmbr_autre_2p,
    heb_tarif_chmbr_autre_3p,
    heb_coordonnee,
    heb_charge_fk,
    heb_gps_long,
    heb_gps_lat,
    heb_maison_tourisme_fk,
    heb_id,
    heb_ecr_date_ouverture,
    heb_ecr_remarque,
    heb_seminaire_vert_fr,
    heb_seminaire_vert_nl,
    heb_seminaire_vert_uk,
    heb_seminaire_vert_de,
    heb_seminaire_vert_it,
    heb_calendrier_proprio,
    heb_maj_info_etat,
    heb_calendrier_proprio_date_maj,
    heb_date_creation,
    heb_date_modification,
    heb_employe_modification,
    heb_employe_creation,
    heb_location,
    heb_groupement_pk,
    heb_tarif_charge,
    heb_desactivation_alloch,
    heb_url)
VALUES
    (81,
    'GR9114102',
    'La Turbine',
    'Chansin, 10',
    'Durnal',
    'GRNA1153',
    7,
    8,
    3,
    null,
    '1',
    '',
    '3RW',
    '3',
    '190.00',
    '205.00',
    '220.00',
    '250.00',
    '300.00',
    '450.00',
    '125.00',
    'Nettoyage par le locataire ou 40.00',
    'Maison de caractere situee dans un site tres calme de 9 ha pres d''une 
    riviere. Nombreuses promenades a faire (a pied et en Vtt)',
    'House full of character situated on a very peaceful site of 9ha close to a 
    river. Numerous different walks to go on (by foot or mountain bike)',
    'Karaktervol huis op een zeer rustig domein van 9 ha, dichtbij een rivier. 
    Vele mogelijkheden voor wandelingen (te voet en met mountain bike)',
    'Stilvolles Haus in sehr ruhigem Anwesen von 9 ha bei einem FluB. 
    Zahlreiche Moglichkeiten fur Wanderungen (zu FuB oder mit MT)',
    'Casa ricca di personalita situata in un luogo molto calmo, su un terreno 
    di 9 ettari vicino al fiume. Numerosi percorsi (a piedi e in mountain bike)',
    'a l''oree des bois, isole, sur 2 niveaux',
    'on the edge of a wood, isolated, on 2 floors',
    'aan de rand van het bos, geisoleerd, op 2 niveaus',
    'a l''oree des bois, isole, sur 2 niveaux',
    'a l''oree des bois, isole, sur 2 niveaux',
    null,
    null,
    null,
    null,
    null,
    '707',
    null,
    6,
    1,
    60,
    null,
    null,
    '',
    '20.0',
    '',
    '0.0',
    '15.0',
    '0.0',
    '7.0',
    '0.0',
    '0.0',
    '15.0',
    '0.80/n./p.',
    '',
    '',
    '',
    '450.00',
    '1',
    '2',
    '1',
    '1',
    'salon, coin cuisine, 2 wc, sdb, buanderie, chauffage central. jardin : 
    pelouse, jeux, bbq.',
    'woonk., kookhoek, 2 wc, badk., washok, centr. verwarm. tuin : gazon, 
    spelen, bbq.',
    'salon, coin cuisine, 2 wc, sdb, buanderie, chauffage central. jardin : 
    pelouse, jeux, bbq.',
    'living, kitchenette, 2 toilets, bath room, laundry room, central heating. 
    garden : lawn, games, bbq.',
    'salon, coin cuisine, 2 wc, sdb, buanderie, chauffage central. jardin : 
    pelouse, jeux, bbq.',
    '15.0',
    '5.0',
    '3.0',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    '',
    '',
    '',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'G3',
    1,
    4.966539,
    50.320956000000002,
    null,
    'la-turbine',
    'None',
    '',
    '',
    '',
    '',
    '',
    '',
    'actif',
    'En attente confirmation',
    '2014-03-21',
    null,
    '2014-06-02 14:47:02.118358',
    'mick',
    null,
    '0101000020770D0000F33B4D66BCDD13403DBA111615294940',
    null,
    null,
    'f',
    'www.gitelaturbine.be');
INSERT
    INTO hebergement(heb_pk,
    heb_code_gdw,
    heb_nom,
    heb_adresse,
    heb_localite,
    heb_code_cgt,
    heb_cgt_cap_min,
    heb_cgt_cap_max,
    heb_cgt_nbre_chmbre,
    heb_etat,
    heb_site_public,
    heb_groupe,
    heb_gdw,
    heb_nbre_epis,
    heb_tarif_we_bs,
    heb_tarif_we_ms,
    heb_tarif_we_hs,
    heb_tarif_sem_bs,
    heb_tarif_sem_ms,
    heb_tarif_sem_hs,
    heb_tarif_garantie,
    heb_tarif_divers,
    heb_descriptif_fr,
    heb_descriptif_uk,
    heb_descriptif_nl,
    heb_descriptif_de,
    heb_descriptif_it,
    heb_pointfort_fr,
    heb_pointfort_uk,
    heb_pointfort_nl,
    heb_pointfort_de,
    heb_pointfort_it,
    heb_equipement_fr,
    heb_equipement_uk,
    heb_equipement_nl,
    heb_equipement_de,
    heb_equipement_it,
    heb_photo,
    heb_com_fk,
    heb_cgt_fk,
    heb_typeheb_fk,
    heb_pro_fk,
    heb_theme_fk,
    heb_label_fk,
    heb_tenis_distance,
    heb_nautisme_distance,
    heb_sky_distance,
    heb_rando_distance,
    heb_piscine_distance,
    heb_peche_distance,
    heb_equitation_distance,
    heb_velo_distance,
    heb_vtt_distance,
    heb_ravel_distance,
    heb_taxe_montant,
    heb_forfait_montant,
    heb_tarif_we_3n,
    heb_tarif_we_4n,
    heb_tarif_semaine_fin_annee,
    heb_lit_1p,
    heb_lit_2p,
    heb_lit_sup,
    heb_lit_enf,
    heb_distribution_fr,
    heb_distribution_nl,
    heb_distribution_it,
    heb_distribution_uk,
    heb_distribution_de,
    heb_gare_distance,
    heb_restaurant_distance,
    heb_commerce_distance,
    heb_tarif_chmbr_avec_dej_1p,
    heb_tarif_chmbr_avec_dej_2p,
    heb_tarif_chmbr_avec_dej_3p,
    heb_tarif_chmbr_sans_dej_1p,
    heb_tarif_chmbr_sans_dej_2p,
    heb_tarif_chmbr_sans_dej_3p,
    heb_tarif_chmbr_dej_1p,
    heb_tarif_chmbr_dej_2p,
    heb_tarif_chmbr_dej_3p,
    heb_tarif_chmbr_table_hote_1p,
    heb_tarif_chmbr_table_hote_2p,
    heb_tarif_chmbr_table_hote_3p,
    heb_tarif_chmbr_autre_1p,
    heb_tarif_chmbr_autre_2p,
    heb_tarif_chmbr_autre_3p,
    heb_coordonnee,
    heb_charge_fk,
    heb_gps_long,
    heb_gps_lat,
    heb_maison_tourisme_fk,
    heb_id,
    heb_ecr_date_ouverture,
    heb_ecr_remarque,
    heb_seminaire_vert_fr,
    heb_seminaire_vert_nl,
    heb_seminaire_vert_uk,
    heb_seminaire_vert_de,
    heb_seminaire_vert_it,
    heb_calendrier_proprio,
    heb_maj_info_etat,
    heb_calendrier_proprio_date_maj,
    heb_date_creation,
    heb_date_modification,
    heb_employe_modification,
    heb_employe_creation,
    heb_location,
    heb_groupement_pk,
    heb_tarif_charge,
    heb_desactivation_alloch,
    heb_url)
VALUES
    (1168,
    'GRECR92094961',
    'Les Cardamines',
    'Comognes de Temploux, 16',
    'Temploux',
    'GRNA5403',
    2,
    4,
    1,
    null,
    '1',
    '',
    null,
    null,
    '140.00',
    '140.00',
    '190.00',
    '240.00',
    '240.00',
    '270.00',
    '150.00',
    'Nettoyage par le locataire ou 25.00',
    'Gîte rural au prem',
    'Rural gite on the ',
    'Landelijke gîte op',
    'Ferienhaus auf der',
    'Alloggio rurale si',
    'à l''orée des bois, mitoyen au propriétaire, sur 2 niveaux',
    'on the edge of a wood, adjoining the owner''s residence, on 2 floors',
    'aan de rand van het bos, palend aan de woning van de eigenaar, op 2 niveaus',
    'am Waldsaum, am Eigentümer angrenzend, auf 2 Ebenen',
    'sul limitare di un',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    1,
    1,
    416,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    '',
    '6.00/10.00',
    '',
    '',
    '',
    '0',
    '1',
    '0',
    '0',
    'salon/sam, coin cuisine, sdb, wc. jardin : pelouse, bbq.',
    'woonk./eetk., kookhoek, badk., wc. tuin : gazon, bbq.',
    'salotto/sala da pr',
    'living room/dining',
    'Wohnzimmer/Esszimm',
    null,
    null,
    null,
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'G2',
    3,
    4.7582709999999997,
    50.472681999999999,
    null,
    'les-cardamines',
    'None',
    '',
    'None',
    'None',
    'None',
    'None',
    'None',
    'non actif',
    'confirmé',
    '2011-02-11',
    null,
    '2014-01-06 15:33:57.978199',
    'sylvie',
    null,
    '0101000020770D000057056A317808134035B401D8803C4940',
    null,
    null,
    'f',
    '');


INSERT
    INTO notification(pk,
    origin,
    "table",
    "column",
    table_pk,
    old_value,
    new_value,
    "date",
    treated,
    cmt,
    "user")
VALUES
    (1,
    'PIVOT',
    'hebergement',
    'heb_localite',
    '81',
    'Durnal',
    'Namur',
    '2014-05-30 17:14:16.174077',
    false,
    null,
    null);
